spring.application.name=gateway

spring.ai.openai.api-key=${GROQ_API_KEY}
spring.ai.openai.base-url=https://api.groq.com/openai
spring.ai.openai.chat.options.model=llama-3.1-8b-instant

# Cloud Vector Database (Pinecone) Configuration
spring.ai.vectorstore.pinecone.api-key=${PINECONE_API_KEY}
spring.ai.vectorstore.pinecone.environment=us-east-1-aws
spring.ai.vectorstore.pinecone.index-name=gateway-cache
spring.ai.vectorstore.pinecone.project-id=default

# Cloud PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://ep-bitter-pine-ap3c68qc.c-7.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
spring.datasource.driverClassName=org.postgresql.Driver

# Auto-execute your schema.sql on the remote server
spring.sql.init.mode=always